// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7EDrCyLaFQHQwNY9m-FoopYGcboQaf5M',
    appId: '1:937774630031:web:982569b25f745e7bcadcfa',
    messagingSenderId: '937774630031',
    projectId: 'auth-b3d27',
    authDomain: 'auth-b3d27.firebaseapp.com',
    storageBucket: 'auth-b3d27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj_sFLZZkLp7hsikJJeoTeIa9DeII4S-k',
    appId: '1:937774630031:android:cb5e88d3d092ce44cadcfa',
    messagingSenderId: '937774630031',
    projectId: 'auth-b3d27',
    storageBucket: 'auth-b3d27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwdjRViaBH-EDu2r--wx83mykls8T1WiM',
    appId: '1:937774630031:ios:7e5b4a8c68345ea7cadcfa',
    messagingSenderId: '937774630031',
    projectId: 'auth-b3d27',
    storageBucket: 'auth-b3d27.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwdjRViaBH-EDu2r--wx83mykls8T1WiM',
    appId: '1:937774630031:ios:7e5b4a8c68345ea7cadcfa',
    messagingSenderId: '937774630031',
    projectId: 'auth-b3d27',
    storageBucket: 'auth-b3d27.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7EDrCyLaFQHQwNY9m-FoopYGcboQaf5M',
    appId: '1:937774630031:web:0034980bbe0d61c7cadcfa',
    messagingSenderId: '937774630031',
    projectId: 'auth-b3d27',
    authDomain: 'auth-b3d27.firebaseapp.com',
    storageBucket: 'auth-b3d27.appspot.com',
  );
}
